#!/bin/sh

function create_link
{
    if [ ! -L "node_modules/$1" ]
    then
        if [ -f "src/$1.js" ]
        then
           ln -s "../src/$1.js" "node_modules/$1"
        fi

        if [ -d "src/$1" ]
        then
            ln -s "../src/$1" "node_modules/$1"
        fi

    else
        echo "link already created ($1)"
    fi
}

create_link "store"
create_link "utils"
create_link "constants"
create_link "actions"
create_link "reducers"
create_link "text"
