export const USER_SIGNIN = 'USER_SIGNIN';
export const USER_SIGNUP = 'USER_SIGNUP';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_REGISTER_FAILED = 'USER_REGISTER_FAILED';
export const USER_CREATE_SESSION_FAILED = 'USER_CREATE_SESSION_FAILED';